# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nap_parser_app', '0007_auto_20171129_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(max_length=1000),
        ),
    ]
