# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nap_parser_app', '0010_auto_20171129_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='stock_options',
        ),
    ]
