# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nap_parser_app', '0011_remove_price_stock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stock_options',
            field=models.TextField(default='None', max_length=2000),
        ),
    ]
